#!/usr/bin/env python3
"""claude-free-audit — generated single-file bundle of the `claude_free` package.

DO NOT EDIT THIS FILE BY HAND.

Source of truth: src/claude_free/ in https://github.com/ChenghengLi/claude-free-installer
Regenerate: python tools/build.py

This file is what `claude-free update` and the installers fetch. It has zero
external dependencies — only the Python standard library.

Usage:
  claude-free-audit.py audit [flags...]
  claude-free-audit.py calibrate [flags...]
  claude-free-audit.py --help

See docs/COMMANDS.md and docs/AUDIT.md for details.
"""

from __future__ import annotations

import argparse
import collections
import json
import math
import os
import re
import statistics
import sys
import time
import urllib.error
import urllib.request
from pathlib import Path
from typing import Optional, Protocol

# ============================================================
# === __init__.py
# ============================================================

__version__ = "0.3.0"

# Last-refreshed marker for the BENCHMARKS table — keep in sync with
# benchmarks.py. Used by the build script to stamp the generated file.
BENCHMARKS_REFRESHED = "2026-05-02"

# ============================================================
# === colors.py
# ============================================================

def colors() -> dict[str, str]:
    """Return a dict of ANSI escape codes, or empty strings if colour is off."""
    if not sys.stdout.isatty() or os.environ.get("NO_COLOR"):
        return {k: "" for k in ("B", "D", "G", "Y", "R", "N")}
    return {
        "B": "\033[1m",   # bold
        "D": "\033[2m",   # dim
        "G": "\033[0;32m",  # green
        "Y": "\033[0;33m",  # yellow
        "R": "\033[0;31m",  # red
        "N": "\033[0m",   # reset
    }

# ============================================================
# === rate_limit.py
# ============================================================

class RateLimiter:
    """Sliding-window rate limiter.

    Free NVIDIA NIM is ~40 req/min/key; we default callers to 30/min to
    leave headroom for the proxy and other concurrent use. Call .wait()
    before every outbound request — it sleeps as needed and returns the
    number of seconds slept (for telemetry).
    """

    def __init__(self, rate_per_min: float):
        self.rate = max(1.0, float(rate_per_min))
        self.window = 60.0
        self.timestamps: collections.deque[float] = collections.deque()

    def _evict(self, now: float) -> None:
        cutoff = now - self.window
        while self.timestamps and self.timestamps[0] < cutoff:
            self.timestamps.popleft()

    def wait(self) -> float:
        now = time.monotonic()
        self._evict(now)
        slept = 0.0
        while len(self.timestamps) >= self.rate:
            wait_for = (self.timestamps[0] + self.window) - now + 0.05
            if wait_for > 0:
                time.sleep(wait_for)
                slept += wait_for
            now = time.monotonic()
            self._evict(now)
        self.timestamps.append(now)
        return slept

# ============================================================
# === env.py
# ============================================================

def env_path() -> Path:
    """Default location of the free-claude-code .env file."""
    return Path.home() / "free-claude-code" / ".env"

def read_env_key(path: Path, key: str) -> Optional[str]:
    """Return the (unquoted, comment-stripped) value of `key` in `path`, or None."""
    if not path.exists():
        return None
    pat = re.compile(rf"^\s*{re.escape(key)}\s*=\s*(.*?)\s*$")
    for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
        m = pat.match(line)
        if not m:
            continue
        v = m.group(1)
        v = v.split("#", 1)[0].strip()
        if (v.startswith('"') and v.endswith('"')) or (v.startswith("'") and v.endswith("'")):
            v = v[1:-1]
        return v
    return None

def write_env_key(path: Path, key: str, value: str) -> None:
    """In-place set `key="value"` in `path`. Creates the file if missing."""
    line = f'{key}="{value}"'
    if not path.exists():
        path.write_text(line + "\n", encoding="utf-8")
        return
    txt = path.read_text(encoding="utf-8")
    pat = re.compile(rf"(?m)^\s*{re.escape(key)}\s*=.*$")
    if pat.search(txt):
        txt = pat.sub(line, txt)
    else:
        if not txt.endswith("\n"):
            txt += "\n"
        txt += line + "\n"
    path.write_text(txt, encoding="utf-8")

def resolve_api_key(provider: str = "nvidia-nim") -> Optional[str]:
    """Look up the API key for `provider` from env vars, then the .env file.

    nvidia-nim   ->  $NVIDIA_NIM_API_KEY > $NVIDIA_API_KEY > .env NVIDIA_NIM_API_KEY
    openrouter   ->  $OPENROUTER_API_KEY > .env OPENROUTER_API_KEY
    """
    if provider == "nvidia-nim":
        for var in ("NVIDIA_NIM_API_KEY", "NVIDIA_API_KEY"):
            v = os.environ.get(var)
            if v:
                return v
        return read_env_key(env_path(), "NVIDIA_NIM_API_KEY")
    if provider == "openrouter":
        v = os.environ.get("OPENROUTER_API_KEY")
        if v:
            return v
        return read_env_key(env_path(), "OPENROUTER_API_KEY")
    return None

# ============================================================
# === benchmarks.py
# ============================================================

# Curated shortlist of code/chat-capable models worth ranking by default.
# Anything not present in the user's account is silently skipped.
# Order = SWE-bench Verified ranking on NVIDIA NIM (May 2026 snapshot).
CURATED = [
    # Frontier (>= 76 SWE-bench Verified)
    "deepseek-ai/deepseek-v4-pro",                  # 80.6
    "minimaxai/minimax-m2.5",                       # 80.2
    "moonshotai/kimi-k2.6",                         # 80.2
    "deepseek-ai/deepseek-v4-flash",                # 79.0
    "minimaxai/minimax-m2.7",                       # 78.0
    "z-ai/glm-5.1",                                 # 78.0 (estimate)
    "z-ai/glm5",                                    # 77.8
    "nvidia/llama-3.3-nemotron-super-49b-v1.5",     # 76.5 (estimate)
    "qwen/qwen3.5-397b-a17b",                       # 76.4
    "nvidia/llama-3.3-nemotron-super-49b-v1",       # 76.4
    # Strong (60-75)
    "moonshotai/kimi-k2-instruct-0905",             # 73.0 (estimate)
    "mistralai/devstral-2-123b-instruct-2512",      # 72.2
    "moonshotai/kimi-k2-thinking",                  # 71.0 (estimate)
    "qwen/qwen3-coder-480b-a35b-instruct",          # 70.0
    "qwen/qwen3.5-122b-a10b",                       # 70.0 (estimate)
    "z-ai/glm4.7",                                  # 70.0 (estimate)
    "nvidia/llama-3.1-nemotron-ultra-253b-v1",      # 68.0 (estimate)
    "deepseek-ai/deepseek-v3.2",                    # 67.8
    "deepseek-ai/deepseek-v3.1-terminus",           # 62.0 (estimate)
    "nvidia/nemotron-3-super-120b-a12b",            # 60.5
    # Mid (35-60)
    "mistralai/mistral-large-3-675b-instruct-2512", # 58.0 (estimate)
    "meta/llama-4-maverick-17b-128e-instruct",      # 55.0 (estimate)
    "qwen/qwen2.5-72b-instruct",                    # 50.0 (LCB)
    "qwen/qwen3-next-80b-a3b-thinking",             # 50.0 (estimate)
    "qwen/qwen2.5-coder-32b-instruct",              # 50.0
    "deepseek-ai/deepseek-r1",                      # 49.2
    "mistralai/mistral-medium-3.5-128b",            # 45.0 (estimate)
    # Lower / fast tier (kept for comparison)
    "openai/gpt-oss-120b",                          # 30.0
    "meta/llama-3.3-70b-instruct",                  # 30.0 (estimate)
    "openai/gpt-oss-20b",                           # 15.0 (estimate)
    "mistralai/mixtral-8x22b-instruct-v0.1",        # 22.0
    "meta/llama-3.1-8b-instruct",                   # 12.0
]

# Last refreshed: 2026-05-02. Vendor model cards / official leaderboards.
BENCHMARKS: dict[str, dict] = {
    # ---- frontier (>= 76) ----
    "deepseek-ai/deepseek-v4-pro":                 {"swebench": 80.6, "code_score": 80.6, "src": "swebench"},
    "minimaxai/minimax-m2.5":                      {"swebench": 80.2, "code_score": 80.2, "src": "swebench"},
    "moonshotai/kimi-k2.6":                        {"swebench": 80.2, "code_score": 80.2, "src": "swebench"},
    "deepseek-ai/deepseek-v4-flash":               {"swebench": 79.0, "code_score": 79.0, "src": "swebench"},
    "minimaxai/minimax-m2.7":                      {"swebench": 78.0, "code_score": 78.0, "src": "swebench"},
    "z-ai/glm-5.1":                                {"swebench": 78.0, "code_score": 78.0, "src": "estimate"},
    "z-ai/glm5":                                   {"swebench": 77.8, "code_score": 77.8, "src": "swebench"},
    "nvidia/llama-3.3-nemotron-super-49b-v1.5":    {"swebench": 76.5, "code_score": 76.5, "src": "estimate"},
    "qwen/qwen3.5-397b-a17b":                      {"swebench": 76.4, "code_score": 76.4, "src": "swebench"},
    "nvidia/llama-3.3-nemotron-super-49b-v1":      {"swebench": 76.4, "livecodebench": 83.6, "code_score": 76.4, "src": "swebench"},
    # ---- strong (60-75) ----
    "moonshotai/kimi-k2-instruct-0905":            {"swebench": 73.0, "code_score": 73.0, "src": "estimate"},
    "mistralai/devstral-2-123b-instruct-2512":     {"swebench": 72.2, "code_score": 72.2, "src": "swebench"},
    "moonshotai/kimi-k2-thinking":                 {"swebench": 71.0, "code_score": 71.0, "src": "estimate"},
    "qwen/qwen3-coder-480b-a35b-instruct":         {"swebench": 70.0, "code_score": 70.0, "src": "swebench"},
    "moonshotai/kimi-k2-instruct":                 {"swebench": 70.0, "code_score": 70.0, "src": "estimate"},
    "qwen/qwen3.5-122b-a10b":                      {"swebench": 70.0, "code_score": 70.0, "src": "estimate"},
    "z-ai/glm4.7":                                 {"livecodebench": 84.9, "humaneval": 94.2, "code_score": 70.0, "src": "estimate"},
    "nvidia/llama-3.1-nemotron-ultra-253b-v1":     {"swebench": 68.0, "code_score": 68.0, "src": "estimate"},
    "deepseek-ai/deepseek-v3.2":                   {"swebench": 67.8, "code_score": 67.8, "src": "swebench"},
    "deepseek-ai/deepseek-v3":                     {"swebench": 67.8, "code_score": 67.8, "src": "swebench"},
    "deepseek-ai/deepseek-v3.1-terminus":          {"swebench": 62.0, "code_score": 62.0, "src": "estimate"},
    "nvidia/nemotron-3-super-120b-a12b":           {"swebench": 60.5, "code_score": 60.5, "src": "swebench"},
    # ---- mid (35-60) ----
    "mistralai/mistral-large-3-675b-instruct-2512":{"swebench": 58.0, "code_score": 58.0, "src": "estimate"},
    "meta/llama-4-maverick-17b-128e-instruct":     {"swebench": 55.0, "code_score": 55.0, "src": "estimate"},
    "qwen/qwen2.5-72b-instruct":                   {"livecodebench": 55.5, "humaneval": 86.6, "code_score": 50.0, "src": "livecodebench"},
    "qwen/qwen3-next-80b-a3b-thinking":            {"swebench": 50.0, "code_score": 50.0, "src": "estimate"},
    "qwen/qwen2.5-coder-32b-instruct":             {"livecodebench": 38.0, "humaneval": 92.7, "code_score": 50.0, "src": "estimate"},
    "deepseek-ai/deepseek-r1":                     {"swebench": 49.2, "livecodebench": 65.9, "code_score": 49.2, "src": "swebench"},
    "mistralai/mistral-medium-3.5-128b":           {"swebench": 45.0, "code_score": 45.0, "src": "estimate"},
    "meta/llama-3.1-405b-instruct":                {"livecodebench": 85.0, "humaneval": 89.0, "code_score": 45.0, "src": "estimate"},
    "mistralai/mistral-medium-3-instruct":         {"swebench": 40.0, "code_score": 40.0, "src": "estimate"},
    # ---- lower / fast tier (<= 35) ----
    "meta/llama-3.3-70b-instruct":                 {"livecodebench": 33.3, "humaneval": 88.4, "code_score": 30.0, "src": "estimate"},
    "mistralai/mistral-large-2-instruct":          {"swebench": 30.0, "humaneval": 92.0, "code_score": 32.0, "src": "estimate"},
    "qwen/qwen3-next-80b-a3b-instruct":            {"swebench": 30.0, "code_score": 30.0, "src": "swebench"},
    "openai/gpt-oss-120b":                         {"swebench": 30.0, "livecodebench": 60.0, "code_score": 30.0, "src": "swebench"},
    "nvidia/llama-3.1-nemotron-70b-instruct":      {"humaneval": 80.0, "code_score": 30.0, "src": "estimate"},
    "01-ai/yi-large":                              {"humaneval": 81.8, "code_score": 28.0, "src": "estimate"},
    "meta/llama-3.1-70b-instruct":                 {"livecodebench": 28.5, "humaneval": 80.5, "code_score": 25.0, "src": "estimate"},
    "google/gemma-3-27b-it":                       {"humaneval": 80.0, "code_score": 25.0, "src": "estimate"},
    "mistralai/mixtral-8x22b-instruct-v0.1":       {"livecodebench": 25.0, "humaneval": 75.0, "code_score": 22.0, "src": "estimate"},
    "google/gemma-2-27b-it":                       {"humaneval": 71.0, "code_score": 18.0, "src": "estimate"},
    "openai/gpt-oss-20b":                          {"swebench": 15.0, "code_score": 15.0, "src": "estimate"},
    "meta/llama-3.1-8b-instruct":                  {"humaneval": 72.6, "code_score": 12.0, "src": "estimate"},
}

def code_score_for(model: str) -> Optional[dict]:
    """Return {'score': float, 'src': str, ...} for a model, or None if unknown."""
    b = BENCHMARKS.get(model)
    if not b:
        return None
    return {
        "score": b.get("code_score"),
        "src": b.get("src", "?"),
        "swebench": b.get("swebench"),
        "livecodebench": b.get("livecodebench"),
        "humaneval": b.get("humaneval"),
    }

def combined_score(code: Optional[float], ttft_ms: Optional[int], tau_ms: float) -> Optional[float]:
    """Combine quality + speed using TTFT only. Higher = better.

    combined = code_score * exp(-TTFT_ms / tau_ms)

    At TTFT=tau, you keep ~37% of the model's quality score. tau=3000ms means
    a 3s TTFT discounts a model heavily, while sub-300ms keeps ~90% of credit.

    This formula ignores tok/s (post-TTFT generation speed). For a metric
    that accounts for both, use smart_score().
    """
    if code is None or ttft_ms is None:
        return None
    return code * math.exp(-ttft_ms / tau_ms)

# Floor for measured tok/s in smart_score. Our probes use max_tokens=16, which
# makes tok/s readings noisy — a real production model averaging 80 tok/s might
# look like 2 tok/s on the probe because the first few chunks dominate.
# Treating anything below this floor as "the floor" prevents probe noise from
# tanking otherwise-good models. Real models on free NIM stream at 10+ tok/s
# steady-state once warmed up.
_TOK_PER_S_FLOOR = 10.0

def smart_score(
    code: Optional[float],
    ttft_ms: Optional[int],
    tok_per_s: Optional[float],
    tau_ms: float,
    output_tokens: int = 200,
) -> Optional[float]:
    """Combine quality + end-to-end response time. Higher = better.

    smart = code_score * exp(-effective_ms / tau_ms)
    where effective_ms = TTFT_ms + (output_tokens / max(tok_per_s, FLOOR)) * 1000

    Models the user's wait for a typical Claude Code response (default 200
    output tokens — medium response length). A model with great TTFT but
    abnormally slow throughput gets penalized just like one with poor TTFT
    — both leave the user staring at the screen.

    The tok/s floor (10/s) prevents noisy probe measurements from trashing
    a model. With max_tokens=16 probes we routinely see 1-3 tok/s for models
    that stream at 50-200 tok/s in production; the floor stops that from
    dominating the ranking.

    If tok_per_s is missing entirely, falls back to combined_score (TTFT-only).
    """
    if code is None or ttft_ms is None:
        return None
    if tok_per_s is None or tok_per_s <= 0:
        return combined_score(code, ttft_ms, tau_ms)
    effective_tps = max(tok_per_s, _TOK_PER_S_FLOOR)
    effective_ms = ttft_ms + (output_tokens / effective_tps) * 1000.0
    # effective_ms is typically 10-30x larger than ttft_ms (most of the time
    # is spent generating tokens, not waiting for the first one). Scale tau
    # by 10 internally so the same --tau value produces sensible numbers for
    # both combined (TTFT-only) and smart (TTFT + output time). With tau=3000,
    # smart's effective tau is 30000ms — a 30s end-to-end response keeps 37%.
    smart_tau = tau_ms * 10
    return code * math.exp(-effective_ms / smart_tau)

# ============================================================
# === providers/base.py
# ============================================================

# Heuristics for non-chat endpoints we should never probe with /chat/completions.
NON_CHAT_PATTERNS = re.compile(
    r"(embed|rerank|guard|nemoguard|safety|nv-embed|colpali|"
    r"asr|speech|tts|riva|stable-diffusion|sdxl|flux|"
    r"vision-only|nv-clip|clip-)",
    re.I,
)

class Provider(Protocol):
    """One inference backend. Implementations live in this package."""

    name: str
    """Short CLI-friendly identifier, e.g. 'nvidia-nim'."""

    api_base: str
    """Base URL, e.g. 'https://integrate.api.nvidia.com/v1'."""

    proxy_value_prefix: str
    """The string that goes before the model id when writing to .env.
    E.g. 'nvidia_nim/' -> a model 'meta/llama-3' becomes 'nvidia_nim/meta/llama-3'.
    Empty string for providers that use the model id verbatim."""

    def __init__(self, api_key: str): ...

    def list_models(self, timeout: float = 15.0) -> list[str]:
        """Return all model ids available to this key."""
        ...

    def probe(
        self,
        model: str,
        timeout: float,
        rate_limiter: Optional[RateLimiter] = None,
        retry_on_429: bool = True,
    ) -> dict:
        """Send one short streaming chat request, return TTFT + tokens.

        Returns a dict with one of:
        - on success: {model, ttft_ms, total_ms, tokens, tok_per_s, sample}
        - on failure: {model, error: str}
        """
        ...

# ============================================================
# === providers/nvidia_nim.py
# ============================================================

PROMPT = "Reply with exactly the single word: pong."
MAX_TOKENS = 16

class NvidiaNimProvider:
    """OpenAI-compatible client for NVIDIA NIM."""

    name = "nvidia-nim"
    api_base = "https://integrate.api.nvidia.com/v1"
    proxy_value_prefix = "nvidia_nim/"

    def __init__(self, api_key: str):
        if not api_key:
            raise ValueError("NVIDIA API key is required")
        self.api_key = api_key

    def list_models(self, timeout: float = 15.0) -> list[str]:
        req = urllib.request.Request(
            f"{self.api_base}/models",
            headers={"Authorization": f"Bearer {self.api_key}"},
        )
        with urllib.request.urlopen(req, timeout=timeout) as r:
            data = json.loads(r.read().decode("utf-8"))
        ids = [m.get("id") for m in data.get("data", []) if m.get("id")]
        return sorted(set(ids))

    def probe(
        self,
        model: str,
        timeout: float,
        rate_limiter: Optional[RateLimiter] = None,
        retry_on_429: bool = True,
    ) -> dict:
        body = {
            "model": model,
            "messages": [{"role": "user", "content": PROMPT}],
            "max_tokens": MAX_TOKENS,
            "temperature": 0,
            "stream": True,
        }
        data = json.dumps(body).encode("utf-8")
        req = urllib.request.Request(
            f"{self.api_base}/chat/completions",
            data=data,
            method="POST",
            headers={
                "Authorization": f"Bearer {self.api_key}",
                "Content-Type": "application/json",
                "Accept": "text/event-stream",
            },
        )
        if rate_limiter is not None:
            rate_limiter.wait()
        t0 = time.perf_counter()
        ttft: Optional[float] = None
        tokens = 0
        text_parts: list[str] = []
        try:
            with urllib.request.urlopen(req, timeout=timeout) as r:
                for raw in r:
                    if not raw:
                        continue
                    line = raw.decode("utf-8", errors="replace").strip()
                    if not line.startswith("data:"):
                        continue
                    payload = line[5:].strip()
                    if payload == "[DONE]":
                        continue
                    try:
                        j = json.loads(payload)
                    except json.JSONDecodeError:
                        continue
                    choices = j.get("choices") or []
                    if not choices:
                        continue
                    delta = choices[0].get("delta") or {}
                    chunk = delta.get("content")
                    if chunk:
                        if ttft is None:
                            ttft = time.perf_counter() - t0
                        tokens += 1
                        text_parts.append(chunk)
        except urllib.error.HTTPError as e:
            if e.code == 429 and retry_on_429:
                ra = e.headers.get("Retry-After") if e.headers else None
                try:
                    wait = float(ra) if ra else 5.0
                except (TypeError, ValueError):
                    wait = 5.0
                wait = min(max(wait, 1.0), 30.0)
                time.sleep(wait)
                return self.probe(model, timeout, rate_limiter, retry_on_429=False)
            body_txt = ""
            try:
                body_txt = e.read().decode("utf-8", errors="replace")[:200]
            except Exception:
                pass
            return {"model": model, "error": f"HTTP {e.code} {body_txt}"}
        except urllib.error.URLError as e:
            reason = getattr(e, "reason", e)
            if isinstance(reason, TimeoutError) or "timed out" in str(reason).lower():
                return {"model": model, "error": f"timeout >{timeout:.1f}s"}
            return {"model": model, "error": f"URL {reason}"}
        except TimeoutError:
            return {"model": model, "error": f"timeout >{timeout:.1f}s"}
        except Exception as e:  # noqa: BLE001
            return {"model": model, "error": f"{type(e).__name__}: {e}"}
        total = time.perf_counter() - t0
        return {
            "model": model,
            "ttft_ms": int(ttft * 1000) if ttft is not None else None,
            "total_ms": int(total * 1000),
            "tokens": tokens,
            "tok_per_s": round(tokens / total, 1) if tokens and total > 0 else None,
            "sample": "".join(text_parts)[:60],
        }

# ============================================================
# === providers/openrouter.py
# ============================================================

PROMPT = "Reply with exactly the single word: pong."
MAX_TOKENS = 16

class OpenRouterProvider:
    """OpenAI-compatible client for OpenRouter."""

    name = "openrouter"
    api_base = "https://openrouter.ai/api/v1"
    proxy_value_prefix = "openrouter/"

    def __init__(self, api_key: str):
        if not api_key:
            raise ValueError("OpenRouter API key is required (sk-or-v1-...)")
        self.api_key = api_key
        # OpenRouter recommends setting these to attribute usage. They're
        # optional; we keep the values minimal and override-able from env.
        self.referer = os.environ.get(
            "OPENROUTER_HTTP_REFERER",
            "https://github.com/ChenghengLi/claude-free-installer",
        )
        self.app_title = os.environ.get("OPENROUTER_X_TITLE", "claude-free-audit")

    def _headers(self) -> dict[str, str]:
        return {
            "Authorization": f"Bearer {self.api_key}",
            "Content-Type": "application/json",
            "Accept": "text/event-stream",
            "HTTP-Referer": self.referer,
            "X-Title": self.app_title,
        }

    def list_models(self, timeout: float = 15.0) -> list[str]:
        req = urllib.request.Request(
            f"{self.api_base}/models",
            headers={"Authorization": f"Bearer {self.api_key}"},
        )
        with urllib.request.urlopen(req, timeout=timeout) as r:
            data = json.loads(r.read().decode("utf-8"))
        ids = [m.get("id") for m in data.get("data", []) if m.get("id")]
        return sorted(set(ids))

    def probe(
        self,
        model: str,
        timeout: float,
        rate_limiter: Optional[RateLimiter] = None,
        retry_on_429: bool = True,
    ) -> dict:
        body = {
            "model": model,
            "messages": [{"role": "user", "content": PROMPT}],
            "max_tokens": MAX_TOKENS,
            "temperature": 0,
            "stream": True,
        }
        data = json.dumps(body).encode("utf-8")
        headers = self._headers()
        # OpenRouter's chat endpoint is /chat/completions, same shape as OpenAI.
        req = urllib.request.Request(
            f"{self.api_base}/chat/completions",
            data=data,
            method="POST",
            headers=headers,
        )
        if rate_limiter is not None:
            rate_limiter.wait()
        t0 = time.perf_counter()
        ttft: Optional[float] = None
        tokens = 0
        text_parts: list[str] = []
        try:
            with urllib.request.urlopen(req, timeout=timeout) as r:
                for raw in r:
                    if not raw:
                        continue
                    line = raw.decode("utf-8", errors="replace").strip()
                    # OpenRouter sometimes emits SSE comments (lines starting
                    # with ":") to keep the connection alive — ignore those.
                    if not line.startswith("data:"):
                        continue
                    payload = line[5:].strip()
                    if payload == "[DONE]":
                        continue
                    try:
                        j = json.loads(payload)
                    except json.JSONDecodeError:
                        continue
                    choices = j.get("choices") or []
                    if not choices:
                        continue
                    delta = choices[0].get("delta") or {}
                    chunk = delta.get("content")
                    if chunk:
                        if ttft is None:
                            ttft = time.perf_counter() - t0
                        tokens += 1
                        text_parts.append(chunk)
        except urllib.error.HTTPError as e:
            if e.code == 429 and retry_on_429:
                ra = e.headers.get("Retry-After") if e.headers else None
                try:
                    wait = float(ra) if ra else 5.0
                except (TypeError, ValueError):
                    wait = 5.0
                wait = min(max(wait, 1.0), 30.0)
                time.sleep(wait)
                return self.probe(model, timeout, rate_limiter, retry_on_429=False)
            body_txt = ""
            try:
                body_txt = e.read().decode("utf-8", errors="replace")[:200]
            except Exception:
                pass
            return {"model": model, "error": f"HTTP {e.code} {body_txt}"}
        except urllib.error.URLError as e:
            reason = getattr(e, "reason", e)
            if isinstance(reason, TimeoutError) or "timed out" in str(reason).lower():
                return {"model": model, "error": f"timeout >{timeout:.1f}s"}
            return {"model": model, "error": f"URL {reason}"}
        except TimeoutError:
            return {"model": model, "error": f"timeout >{timeout:.1f}s"}
        except Exception as e:  # noqa: BLE001
            return {"model": model, "error": f"{type(e).__name__}: {e}"}
        total = time.perf_counter() - t0
        return {
            "model": model,
            "ttft_ms": int(ttft * 1000) if ttft is not None else None,
            "total_ms": int(total * 1000),
            "tokens": tokens,
            "tok_per_s": round(tokens / total, 1) if tokens and total > 0 else None,
            "sample": "".join(text_parts)[:60],
        }

# ============================================================
# === providers/__init__.py
# ============================================================

# Registry of available providers. Keys are CLI-friendly short names.
_PROVIDERS: dict[str, type[Provider]] = {
    "nvidia-nim": NvidiaNimProvider,
    "openrouter": OpenRouterProvider,
}

def register_providers() -> dict[str, type[Provider]]:
    """Return the provider registry. Mutate to add more."""
    return _PROVIDERS

def get_provider(name: str) -> type[Provider]:
    if name not in _PROVIDERS:
        raise KeyError(f"Unknown provider: {name!r}. Known: {list(_PROVIDERS)}")
    return _PROVIDERS[name]

# ============================================================
# === measure.py
# ============================================================

def _median(values: list[int]) -> int:
    return int(statistics.median(values))

def measure(
    provider: Provider,
    model: str,
    runs: int,
    timeout: float,
    do_warmup: bool,
    rate_limiter: Optional[RateLimiter] = None,
    warmup_timeout: Optional[float] = None,
) -> dict:
    """Warmup + `runs` measured probes. Returns aggregated stats or {error: str}."""
    if do_warmup:
        # Cold-start can be much slower than steady-state on NIM (some models
        # take 60-90s on first call). Give the warmup a bigger budget than
        # measured runs so we don't blackball slow-cold/fast-warm models.
        wt = warmup_timeout if warmup_timeout is not None else max(timeout * 2.5, 90.0)
        provider.probe(model, wt, rate_limiter=rate_limiter)  # discard
    samples: list[dict] = []
    for _ in range(runs):
        samples.append(provider.probe(model, timeout, rate_limiter=rate_limiter))
    ok = [s for s in samples if not s.get("error") and s.get("ttft_ms") is not None]
    if not ok:
        first_err = next((s for s in samples if s.get("error")), {"error": "no successful runs"})
        return {"model": model, "error": first_err.get("error")}
    ttfts = [s["ttft_ms"] for s in ok]
    totals = [s["total_ms"] for s in ok]
    tpss = [s["tok_per_s"] for s in ok if s.get("tok_per_s")]
    return {
        "model": model,
        "ttft_ms": _median(ttfts),
        "ttft_min_ms": min(ttfts),
        "ttft_max_ms": max(ttfts),
        "total_ms": _median(totals),
        "tok_per_s": round(statistics.mean(tpss), 1) if tpss else None,
        "samples": len(ok),
        "sample_text": ok[-1].get("sample", ""),
    }

# ============================================================
# === commands/__init__.py
# ============================================================



# ============================================================
# === commands/audit.py
# ============================================================

def select_candidates(args: argparse.Namespace, available: list[str]) -> list[str]:
    """Build the candidate list from CLI flags + the available model set."""
    chat_only = [m for m in available if not NON_CHAT_PATTERNS.search(m)]

    if args.early_exit:
        # Quality-priority walk: every benchmarked model present in the
        # account, sorted by code_score descending. We use BENCHMARKS as
        # the source of truth so calibrate sees every known model regardless
        # of CURATED ordering.
        if args.filter:
            f = args.filter.lower()
            base = [m for m in chat_only if f in m.lower() and m in BENCHMARKS]
        else:
            base = [m for m in BENCHMARKS if m in chat_only]
        cands = sorted(base, key=lambda m: -(BENCHMARKS[m].get("code_score") or 0))
    elif args.all:
        cands = chat_only
    elif args.filter:
        f = args.filter.lower()
        cands = [m for m in chat_only if f in m.lower()]
    else:
        cands = [m for m in CURATED if m in chat_only]

    for extra in args.include:
        if extra in available and extra not in cands:
            cands.append(extra)

    seen: set[str] = set()
    out: list[str] = []
    for m in cands:
        if m in seen:
            continue
        seen.add(m)
        out.append(m)
        if len(out) >= args.max:
            break
    return out

def _maybe_write_env(
    args: argparse.Namespace,
    env_file: Path,
    proxy_value: str,
    C: dict[str, str],
) -> None:
    if args.no_set:
        print(f"{C['D']}--no-set: leaving {env_file} alone.{C['N']}")
        return
    if not env_file.exists():
        print(
            f"{C['Y']}Skipping .env update: {env_file} not found "
            f"(install claude-free first).{C['N']}"
        )
        return
    if not args.auto_set:
        try:
            ans = input(
                f"\nSet {C['B']}MODEL_OPUS / MODEL_SONNET / MODEL_HAIKU / MODEL{C['N']} "
                f"to {C['G']}{proxy_value}{C['N']} in {env_file}? [Y/n] "
            ).strip().lower()
        except EOFError:
            ans = ""
        if ans not in ("", "y", "yes"):
            print("Skipped -- .env unchanged.")
            return
    for k in ("MODEL_OPUS", "MODEL_SONNET", "MODEL_HAIKU", "MODEL"):
        write_env_key(env_file, k, proxy_value)
    print(f"{C['G']}Updated {env_file}.{C['N']}")
    print(
        f"{C['D']}Restart any running proxy: `claude-free stop && claude-free` "
        f"to pick up the new tier mapping.{C['N']}"
    )

def _early_exit_path(
    args: argparse.Namespace,
    provider: Provider,
    candidates: list[str],
    limiter: Optional[RateLimiter],
    env_file: Path,
    C: dict[str, str],
) -> int:
    """Quality-priority walk: stop at first model whose TTFT <= threshold."""
    threshold = args.threshold if args.threshold > 0 else 1000.0
    measured_timeout = (threshold / 1000.0) + 0.5
    warmup_timeout = max(measured_timeout * 5, 10.0)
    ee_runs = 1
    print(
        f"  walking {len(candidates)} benchmarked model(s) by code-score desc, "
        f"first one with TTFT <= {C['G']}{threshold:.0f} ms{C['N']} wins\n"
        f"  {C['D']}per-probe timeout: warmup {warmup_timeout:.0f}s, measured "
        f"{measured_timeout:.1f}s, {ee_runs} measured run/model{C['N']}\n"
    )
    winner_record: Optional[dict] = None
    all_results: list[dict] = []
    for i, m in enumerate(candidates, 1):
        bench = code_score_for(m) or {}
        cs = bench.get("score")
        cs_str = f"{cs:.1f}" if cs is not None else "n/a"
        print(
            f"  [{i:>2}/{len(candidates)}] {m:<55} "
            f"code={C['G']}{cs_str:>5}{C['N']}  ",
            end="", flush=True,
        )
        r = measure(
            provider, m, ee_runs, measured_timeout,
            do_warmup=not args.no_warmup,
            rate_limiter=limiter,
            warmup_timeout=warmup_timeout,
        )
        r["code_score"] = cs
        r["code_src"] = bench.get("src")
        all_results.append(r)
        if r.get("error"):
            print(f"{C['R']}{r['error'][:60]}{C['N']}")
            continue
        r["combined"] = combined_score(cs, r.get("ttft_ms"), args.tau)
        r["smart"] = smart_score(cs, r.get("ttft_ms"), r.get("tok_per_s"), args.tau, args.output_tokens)
        ttft = r["ttft_ms"]
        ok_speed = ttft is not None and ttft <= threshold
        tag = f"{C['G']}WINNER{C['N']}" if ok_speed else f"{C['Y']}slow{C['N']}"
        print(
            f"TTFT {C['B']}{ttft:>5} ms{C['N']}  "
            f"({r['samples']} runs)  -> {tag}"
        )
        if ok_speed:
            winner_record = r
            break

    if winner_record is None:
        ok = [
            r for r in all_results
            if not r.get("error")
            and r.get("ttft_ms") is not None
            and r.get("combined") is not None
        ]
        if not ok:
            print(f"\n{C['R']}No model met threshold and no successful probes either.{C['N']}")
            return 1
        ok.sort(key=lambda r: -r["combined"])
        winner_record = ok[0]
        print(
            f"\n{C['Y']}No model met TTFT <= {threshold:.0f} ms. "
            f"Falling back to best combined score: {winner_record['model']} "
            f"(TTFT {winner_record['ttft_ms']} ms, code {winner_record.get('code_score')}).{C['N']}"
        )

    winner = winner_record["model"]
    proxy_value = winner if winner.startswith(provider.proxy_value_prefix) else f"{provider.proxy_value_prefix}{winner}"
    print(
        f"\n{C['B']}Picked:{C['N']} {C['G']}{winner}{C['N']}  "
        f"(TTFT {winner_record['ttft_ms']} ms, code {winner_record.get('code_score')}, "
        f"src {winner_record.get('code_src', '?')})"
    )
    print(f"  -> {proxy_value}")
    _maybe_write_env(args, env_file, proxy_value, C)
    return 0

def _full_sweep_path(
    args: argparse.Namespace,
    provider: Provider,
    candidates: list[str],
    limiter: Optional[RateLimiter],
    env_file: Path,
    C: dict[str, str],
) -> int:
    """Probe every candidate, print three rankings (TTFT / code / combined)."""
    runs = max(1, args.runs)
    print(
        f"  probing {len(candidates)} model(s), "
        f"{'no warmup, ' if args.no_warmup else '1 warmup + '}{runs} measured run(s) each, "
        f"timeout {args.timeout:.0f}s\n"
    )

    width = max(len(m) for m in candidates) + 2
    width = min(width, 55)
    header = (
        f"  {'MODEL':<{width}}  {'TTFT(ms)':>10}  {'TOK/S':>7}  "
        f"{'CODE':>6}  {'SMART':>7}  SRC"
    )
    print(f"{C['B']}{header}{C['N']}")
    print("  " + "-" * (width + 50))

    results: list[dict] = []
    for m in candidates:
        print(f"  {m:<{width}}  ", end="", flush=True)
        r = measure(
            provider, m, runs, args.timeout,
            do_warmup=not args.no_warmup,
            rate_limiter=limiter,
        )
        bench = code_score_for(m)
        if bench:
            r["code_score"] = bench["score"]
            r["code_src"] = bench["src"]
            r["bench_detail"] = bench
        if r.get("error"):
            print(f"{C['R']}ERROR{C['N']}  {r['error'][:80]}")
        else:
            r["combined"] = combined_score(r.get("code_score"), r.get("ttft_ms"), args.tau)
            r["smart"] = smart_score(
                r.get("code_score"), r.get("ttft_ms"), r.get("tok_per_s"),
                args.tau, args.output_tokens,
            )
            cs = r.get("code_score")
            sm = r.get("smart")
            cs_str = f"{cs:.1f}" if cs is not None else "-"
            sm_str = f"{sm:.1f}" if sm is not None else "-"
            tok = r.get("tok_per_s")
            tok_str = f"{tok}" if tok is not None else "-"
            print(
                f"{r['ttft_ms']:>10}  "
                f"{tok_str:>7}  "
                f"{cs_str:>6}  "
                f"{sm_str:>7}  "
                f"{r.get('code_src', '?')}"
            )
        results.append(r)

    ok = [r for r in results if not r.get("error") and r.get("ttft_ms") is not None]
    if not ok:
        print(f"\n{C['R']}No successful probes -- nothing to rank.{C['N']}")
        return 1

    def _print_ranking(title, sorted_list, score_fn, score_label):
        print(f"\n{C['B']}{title}:{C['N']}")
        for i, r in enumerate(sorted_list, 1):
            marker = "*" if i == 1 else " "
            score = score_fn(r)
            score_str = f"{score:.1f}" if isinstance(score, float) else str(score)
            print(
                f"  {marker} {i:>2}. {r['model']:<{width}}  "
                f"{C['G']}{score_str:>7}{C['N']}  {score_label}  "
                f"({C['D']}TTFT {r['ttft_ms']} ms, "
                f"code {r.get('code_score') if r.get('code_score') is not None else 'n/a'}{C['N']})"
            )

    by_ttft = sorted(ok, key=lambda r: r["ttft_ms"])
    by_code = sorted(
        [r for r in ok if r.get("code_score") is not None],
        key=lambda r: -r["code_score"],
    )
    by_combined = sorted(
        [r for r in ok if r.get("combined") is not None],
        key=lambda r: -r["combined"],
    )
    by_smart = sorted(
        [r for r in ok if r.get("smart") is not None],
        key=lambda r: -r["smart"],
    )

    _print_ranking("Lowest TTFT", by_ttft, lambda r: r["ttft_ms"], "ms")
    if by_code:
        _print_ranking("Best code-benchmark score", by_code, lambda r: r["code_score"], "pts")
    if by_smart:
        _print_ranking(
            f"Smart score (TTFT + {args.output_tokens} output tokens, tau={args.tau:.0f}ms)",
            by_smart,
            lambda r: r["smart"],
            "score",
        )

    if args.by == "smart" and by_smart:
        winner_record = by_smart[0]
        ranking_used = "smart (TTFT + output time)"
    elif args.by == "combined" and by_combined:
        winner_record = by_combined[0]
        ranking_used = "combined (TTFT only)"
    elif args.by == "code" and by_code:
        winner_record = by_code[0]
        ranking_used = "code benchmark"
    else:
        winner_record = by_ttft[0]
        ranking_used = "lowest TTFT"
        if args.by != "ttft":
            print(
                f"\n{C['Y']}note: --by {args.by} had no eligible models "
                f"(missing benchmark / throughput data); falling back to TTFT.{C['N']}"
            )

    winner = winner_record["model"]
    proxy_value = winner if winner.startswith(provider.proxy_value_prefix) else f"{provider.proxy_value_prefix}{winner}"
    print(
        f"\n{C['B']}Winner ({ranking_used}):{C['N']} {C['G']}{winner}{C['N']}  "
        f"-> {proxy_value}"
    )
    _maybe_write_env(args, env_file, proxy_value, C)
    return 0

def run_audit(args: argparse.Namespace, provider: Provider) -> int:
    """Entry point for `claude-free audit` and `claude-free calibrate`."""
    C = colors()
    env_file = Path(args.env_file) if args.env_file else env_path()
    limiter = RateLimiter(args.rate) if args.rate and args.rate > 0 else None

    print(f"{C['B']}claude-free audit{C['N']}  {C['D']}-- ranking {provider.name} chat models by TTFT and code benchmarks{C['N']}\n")
    if limiter is not None:
        print(f"  {C['D']}rate limit: {args.rate:.0f} req/min sliding window (sleep before bursts){C['N']}")

    print(f"  fetching model catalogue from {provider.api_base}/models ...", end=" ", flush=True)
    try:
        available = provider.list_models()
    except Exception as e:  # noqa: BLE001
        print(f"{C['R']}failed{C['N']}: {e}")
        return 1
    print(f"{C['G']}{len(available)} models{C['N']}")

    candidates = select_candidates(args, available)
    if not candidates:
        print(f"{C['Y']}No matching models. Try --all or --filter <substr>.{C['N']}")
        return 1

    if args.early_exit:
        return _early_exit_path(args, provider, candidates, limiter, env_file, C)
    return _full_sweep_path(args, provider, candidates, limiter, env_file, C)

# ============================================================
# === commands/update.py
# ============================================================

URL = "https://raw.githubusercontent.com/ChenghengLi/claude-free-installer/main/claude-free-audit.py"

def run_update(_args, _provider) -> int:
    print(
        "claude-free update -- in development mode, run one of these to refresh "
        "the deployed single-file artifact:\n\n"
        f"  Linux/macOS: curl -fsSL {URL} -o ~/.local/bin/claude-free-audit.py\n"
        f"  Windows:     iwr {URL} -OutFile $HOME\\.local\\bin\\claude-free-audit.py\n\n"
        "Or, in a development checkout, regenerate it locally:\n\n"
        "  python tools/build.py\n"
    )
    return 0

# ============================================================
# === cli.py
# ============================================================

def _build_audit_parser(p: argparse.ArgumentParser) -> None:
    """Add the audit/calibrate flags. calibrate is `audit --set --early-exit`."""
    p.add_argument("--all", action="store_true", help="probe every chat-capable model in your account")
    p.add_argument("--filter", default="", help="only probe model ids containing this substring")
    p.add_argument("--include", action="append", default=[], help="add a specific model id (repeatable)")
    p.add_argument("--runs", type=int, default=3, help="measured runs per model after 1 warmup (default 3)")
    p.add_argument("--timeout", type=float, default=45.0, help="per-probe timeout in seconds (default 45)")
    p.add_argument("--max", type=int, default=15, help="max number of models to probe (default 15)")
    p.add_argument("--no-warmup", action="store_true", help="skip the warmup probe")
    p.add_argument(
        "--by",
        choices=("smart", "combined", "ttft", "code"),
        default="smart",
        help=(
            "rank winner by: smart (default, code * exp(-(TTFT + output/tok_per_s) / tau)), "
            "combined (TTFT-only variant), ttft (fastest), or code (best benchmarks)"
        ),
    )
    p.add_argument(
        "--tau",
        type=float,
        default=3000.0,
        help="latency penalty constant in ms (default 3000). lower = penalize slow models harder",
    )
    p.add_argument(
        "--output-tokens",
        type=int,
        default=200,
        help="typical response length used by smart_score (default 200 tokens)",
    )
    p.add_argument(
        "--early-exit",
        action="store_true",
        help="walk every benchmarked model in code-score-desc order; stop at first model with TTFT <= --threshold",
    )
    p.add_argument(
        "--threshold",
        type=float,
        default=0.0,
        help="TTFT threshold in ms for --early-exit (default 1000 when --early-exit, else off)",
    )
    p.add_argument(
        "--rate",
        type=float,
        default=30.0,
        help="max requests/min to the provider (default 30; free NIM ceiling is ~40). 0 = no limit",
    )
    g = p.add_mutually_exclusive_group()
    g.add_argument("--set", dest="auto_set", action="store_true", help="auto-set winner to all tiers (no prompt)")
    g.add_argument("--no-set", dest="no_set", action="store_true", help="never offer to set the winner")
    p.add_argument("--key", help="provider API key (overrides env / .env)")
    p.add_argument(
        "--provider",
        default="nvidia-nim",
        choices=list(register_providers().keys()),
        help="which inference provider to probe (default: nvidia-nim)",
    )
    p.add_argument("--env-file", help="path to free-claude-code .env (default ~/free-claude-code/.env)")

def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        prog="claude-free-audit",
        description="Audit, calibrate, and switch NVIDIA NIM models for Claude Code.",
    )
    p.add_argument("--version", action="version", version=f"claude-free-audit {__version__}")
    sub = p.add_subparsers(dest="command")

    p_audit = sub.add_parser(
        "audit",
        help="probe models for TTFT + code benchmarks, print three rankings",
    )
    _build_audit_parser(p_audit)

    p_calibrate = sub.add_parser(
        "calibrate",
        help="walk by code-score, pick first model with TTFT <= 1s, write to .env",
    )
    _build_audit_parser(p_calibrate)

    sub.add_parser("update", help="show how to refresh the deployed audit script")

    # Back-compat: if no subcommand, accept all the audit flags directly
    # (so `claude-free-audit.py --early-exit ...` keeps working as before
    # without an explicit `audit` subcommand).
    _build_audit_parser(p)
    return p

def main(argv: list[str]) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)

    if args.command == "update":
        return run_update(args, None)

    # calibrate is audit with extra defaults baked in
    if args.command == "calibrate":
        if not args.early_exit:
            args.early_exit = True
        if args.threshold == 0:
            args.threshold = 1000.0
        if not args.auto_set and not args.no_set:
            args.auto_set = True

    api_key = args.key or resolve_api_key(args.provider)
    if not api_key:
        env_var = {
            "nvidia-nim": "NVIDIA_NIM_API_KEY",
            "openrouter": "OPENROUTER_API_KEY",
        }.get(args.provider, args.provider.upper().replace("-", "_") + "_API_KEY")
        print(
            f"No API key for provider '{args.provider}'. "
            f"Set ${env_var} or populate ~/free-claude-code/.env, "
            f"or pass --key.",
            file=sys.stderr,
        )
        return 2

    provider_cls = get_provider(args.provider)
    provider = provider_cls(api_key)
    return run_audit(args, provider)



if __name__ == "__main__":
    import sys
    sys.exit(main(sys.argv[1:]))
