"""claude_free — audit, calibrate, and switch NVIDIA NIM models for Claude Code.

This package is the canonical source for `claude-free-audit.py` (the deployed
single-file artifact at the repo root). The deployed file is generated by
`tools/build.py` from the modules here.

If you're reading this in development, you can run the package directly:

    python -m claude_free audit
    python -m claude_free calibrate

The single-file version is what `claude-free` invokes in production.
"""

__version__ = "0.3.0"

# Last-refreshed marker for the BENCHMARKS table — keep in sync with
# benchmarks.py. Used by the build script to stamp the generated file.
BENCHMARKS_REFRESHED = "2026-05-02"
