"""Bundle src/claude_free/ into the deployed single-file `claude-free-audit.py`.

The deployed file is what `claude-free update` and the installers fetch from
GitHub. It has to be a single self-contained Python file with no external
deps — even `claude_free` itself, since we don't want to make users
`pip install` anything.

Strategy: concatenate the package modules in dependency order, strip the
`from claude_free.X import Y` lines (everything's in the same file), dedup
the stdlib imports, prepend a shebang and a "DO NOT EDIT — generated from
src/claude_free/" header.

Run: `python tools/build.py [--check]`

  --check   compare current claude-free-audit.py to a fresh build; exit 1
            if they differ. Useful in CI.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "src" / "claude_free"
OUT = ROOT / "claude-free-audit.py"

# Module concatenation order. Earlier modules can be referenced by later ones.
MODULE_ORDER = [
    "__init__.py",
    "colors.py",
    "rate_limit.py",
    "env.py",
    "benchmarks.py",
    "providers/base.py",
    "providers/nvidia_nim.py",
    "providers/openrouter.py",
    "providers/__init__.py",
    "measure.py",
    "commands/__init__.py",
    "commands/audit.py",
    "commands/update.py",
    "cli.py",
]

# Imports we need at the top of the bundled file. Inferred from scanning the
# source rather than hardcoded — if a module starts using `import X`, the
# bundler picks it up automatically.
#
# IMPORT_RE matches:
#   - import X, import X as Y
#   - from MOD import NAME[, NAME]...
#   - from MOD import (NAME, NAME, ...)   spanning multiple lines
IMPORT_RE = re.compile(
    r"^(import \S+(?: as \S+)?|from [a-zA-Z_.][\w.]* import (?:\([^)]*\)|.+))$",
    re.M,
)
# Match multi-line `from MOD import (...)` and single-line `from MOD import a, b`.
INTERNAL_IMPORT_RE = re.compile(
    r"^from claude_free(?:\.[\w.]+)? import (?:\([^)]*\)|.+)$",
    re.M,
)
FUTURE_IMPORT_RE = re.compile(r"^from __future__ import .+$", re.M)
DOCSTRING_RE = re.compile(r'^"""[\s\S]*?"""', re.M)


def read_module(rel_path: str) -> str:
    return (SRC / rel_path).read_text(encoding="utf-8")


def collect_external_imports() -> list[str]:
    """Find every external import across all modules, dedup smartly, return sorted.

    `from X import a` and `from X import b` get merged into `from X import a, b`
    so we don't end up with two lines importing from the same module."""
    plain: set[str] = set()
    froms: dict[str, set[str]] = {}
    for rel in MODULE_ORDER:
        text = read_module(rel)
        for m in IMPORT_RE.finditer(text):
            line = m.group(1).strip()
            if line.startswith("from claude_free") or line.startswith("from __future__"):
                continue
            if line.startswith("import "):
                plain.add(line)
                continue
            # `from MOD import a, b as c, d`
            mod, _, names = line[len("from "):].partition(" import ")
            mod = mod.strip()
            for name in names.split(","):
                froms.setdefault(mod, set()).add(name.strip())
    out = sorted(plain)
    for mod in sorted(froms):
        names = sorted(froms[mod])
        out.append(f"from {mod} import {', '.join(names)}")
    return out


def strip_module(text: str) -> str:
    """Remove module-level docstring + all imports.

    All external imports are collected separately and emitted at the top of the
    bundle; internal imports between modules are unnecessary in the bundle
    because everything ends up in one namespace.
    """
    # Drop the leading docstring.
    text = DOCSTRING_RE.sub("", text, count=1).lstrip("\n")
    # Drop future-imports (one is added at the top of the bundle).
    text = FUTURE_IMPORT_RE.sub("", text)
    # Drop internal imports (multi-line first, since IMPORT_RE would only get
    # the first line of a parenthesized form and leave the rest as a stray block).
    text = INTERNAL_IMPORT_RE.sub("", text)
    # Drop external imports (collected at the top).
    text = IMPORT_RE.sub("", text)
    # Trim consecutive blank lines.
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text.strip() + "\n"


HEADER = '''#!/usr/bin/env python3
"""claude-free-audit — generated single-file bundle of the `claude_free` package.

DO NOT EDIT THIS FILE BY HAND.

Source of truth: src/claude_free/ in https://github.com/ChenghengLi/claude-free-installer
Regenerate: python tools/build.py

This file is what `claude-free update` and the installers fetch. It has zero
external dependencies — only the Python standard library.

Usage:
  claude-free-audit.py audit [flags...]
  claude-free-audit.py calibrate [flags...]
  claude-free-audit.py --help

See docs/COMMANDS.md and docs/AUDIT.md for details.
"""

from __future__ import annotations

'''

FOOTER = '''

if __name__ == "__main__":
    import sys
    sys.exit(main(sys.argv[1:]))
'''


def build() -> str:
    parts = [HEADER]
    for imp in collect_external_imports():
        parts.append(imp + "\n")
    parts.append("\n")
    for rel in MODULE_ORDER:
        parts.append(f"# ============================================================\n")
        parts.append(f"# === {rel}\n")
        parts.append(f"# ============================================================\n\n")
        parts.append(strip_module(read_module(rel)))
        parts.append("\n")
    parts.append(FOOTER)
    return "".join(parts)


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--check", action="store_true", help="exit 1 if claude-free-audit.py is stale")
    args = p.parse_args()

    bundled = build()

    if args.check:
        if not OUT.exists():
            print("claude-free-audit.py is missing; run `python tools/build.py`")
            return 1
        existing = OUT.read_text(encoding="utf-8")
        if existing != bundled:
            print("claude-free-audit.py is stale; run `python tools/build.py`")
            return 1
        print("claude-free-audit.py is up to date.")
        return 0

    OUT.write_text(bundled, encoding="utf-8", newline="\n")
    print(f"wrote {OUT.relative_to(ROOT)} ({len(bundled)} bytes, "
          f"{bundled.count(chr(10))} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
